version: "3"

services:
  app:
    container_name: app
    restart: always
    image: node
    environment:
      PORT: 3000
      MONGODB_URI: "mongodb://mongo:27017"
    networks:
      - database

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - database

networks:
  database: